name: "PR — Evergreen dev→main"

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  ensure-dev-pr:
    name: "Ensure always-open draft PR (dev→main)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure branch 'dev' exists (from main if missing)
        run: |
          set -euo pipefail
          if git ls-remote --heads origin dev | grep -q 'refs/heads/dev'; then
            echo "Branch 'dev' already exists on origin."
          else
            echo "Creating 'dev' from main and pushing to origin..."
            git switch -c dev
            git push origin dev
          fi

      - name: Sync dev with main (fast-forward or merge)
        run: |
          set -euo pipefail
          git fetch origin dev || true
          # If dev exists locally, check it out; otherwise create from origin/dev
          if git show-ref --verify --quiet refs/heads/dev; then
            git switch dev
          else
            git switch -c dev origin/dev
          fi
          # Try to fast-forward dev to main; if diverged, do a merge commit
          git fetch origin main
          if git merge-base --is-ancestor HEAD origin/main; then
            echo "Fast-forwarding dev to main..."
            git merge --ff-only origin/main || true
          else
            echo "Merging main into dev to sync..."
            git merge --no-edit origin/main || true
          fi
          git push origin dev

      - name: Ensure draft PR dev→main exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          REPO="${GITHUB_REPOSITORY}"
          # If an OPEN PR with head=dev exists, no-op.
          if gh pr list --repo "$REPO" --head dev --state open --json number --jq '.[0].number' | grep -q '^[0-9]\+$'; then
            echo "Evergreen PR for 'dev' already exists."
          else
            echo "Creating evergreen draft PR dev→main..."
            gh pr create \
              --repo "$REPO" \
              --head dev \
              --base main \
              --title "evergreen: dev→main (Patch-from-comment inbox)" \
              --body "Always-open DRAFT PR for patch-from-comment diffs. Edit on 'dev' or post diff comments here. Merge when checks are green." \
              --draft
          fi
