name: auth-smoke
on: { workflow_dispatch: {} }
permissions: { id-token: write, contents: read }
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v2
      - run: |
          gcloud auth list
          gcloud config list
          gcloud projects describe ${{ secrets.GCP_PROJECT }} --format="value(projectNumber)"
          gcloud artifacts repositories list \
            --project=${{ secrets.GCP_PROJECT }} --location=${{ secrets.GCP_REGION }}
