name: Patch-from-comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    # Only run on comments on PRs that contain "/patch"
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/patch') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR head info
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const pull_number = context.payload.issue.number;
            const {data: pr} = await github.rest.pulls.get({owner, repo, pull_number});
            core.setOutput('head_repo', pr.head.repo.full_name);
            core.setOutput('head_ref', pr.head.ref);

      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.pr.outputs.head_repo }}
          ref: ${{ steps.pr.outputs.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract fenced patch
        id: extract
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const body = context.payload.comment.body || '';
            const m = body.match(/```(?:patch|diff)?\s*([\s\S]*?)```/i);
            if (!m) {
              core.setFailed('No fenced ```patch``` or ```diff``` block found in the comment.');
              return;
            }
            return m[1];

      - name: Write patch file
        run: |
          set -euo pipefail
          printf "%s" "${{ steps.extract.outputs.result }}" > /tmp/patch.diff
          echo "----- PATCH PREVIEW (first 120 lines) -----"
          sed -n '1,120p' /tmp/patch.diff || true
          echo "------------------------------------------"

      - name: Apply patch & push
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git apply -p0 --whitespace=fix -v /tmp/patch.diff
          git add -A
          git commit -m "Apply /patch from comment $GITHUB_RUN_ID"
          git push origin HEAD

      - name: Comment success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const issue_number = context.payload.issue.number;
            await github.rest.issues.createComment({
              owner, repo, issue_number,
              body: "✅ Patch applied and pushed. (run #" + process.env.GITHUB_RUN_ID + ")"
            });

      - name: Comment failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const issue_number = context.payload.issue.number;
            await github.rest.issues.createComment({
              owner, repo, issue_number,
              body: "❌ Failed to apply patch. See logs. (run #" + process.env.GITHUB_RUN_ID + ")"
            });
