name: z00_secrets_smoke
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check required secrets presence (values not printed)
        run: |
          missing=0
          check() {
            n="$1"; v="$2"
            if [ -z "$v" ]; then
              echo "::error::Missing or empty secret: $n"
              missing=1
            else
              echo "ok: $n is set"
            fi
          }

          # Your secret names
          check "WIF_PROVIDER"        "${{ secrets.WIF_PROVIDER }}"
          check "WIF_SERVICE_ACCOUNT" "${{ secrets.WIF_SERVICE_ACCOUNT }}"
          check "GCP_PROJECT"         "${{ secrets.GCP_PROJECT }}"
          check "GCP_REGION"          "${{ secrets.GCP_REGION }}"
          check "SHEET_ID"            "${{ secrets.SHEET_ID }}"
          check "FRED_API_KEY"        "${{ secrets.FRED_API_KEY }}"

          if [ $missing -ne 0 ]; then
            echo "One or more required secrets are missing."; exit 1
          fi

      - name: Print summary
        run: |
          echo "All required secrets present (values hidden)."
